
LAYOUT_ergodox(
        // left hand
KC_EQL,  KC_1,         KC_2,   KC_3,   KC_4,   KC_5,   KC_LGUI,
KC_DELT, KC_Q,         KC_W,   KC_E,   KC_R,   KC_T,   KC_ESC,
KC_SLSH, KC_A,         KC_S,   KC_D,   KC_F,   KC_G,
KC_LALT, KC_Z,         KC_X,   KC_C,   KC_V,   KC_B,   KC_TAB,
LT(SYMB,KC_GRV),KC_QUOT,      LALT(KC_LSFT),  KC_LEFT,KC_RGHT,
                                                              KC_TILD,  KC_SLSH,
                                                                        KC_INS,
                                                         KC_SPC,KC_LSFT,KC_LCTL,
        // right hand
             KC_RGUI  ,    KC_6,   KC_7,  KC_8,   KC_9,   KC_0,             KC_EQL,
             KC_BSPC ,    KC_Y,   KC_U,  KC_I,   KC_O,   KC_P,             KC_BSLS,
                          KC_H,   KC_J,  KC_K,   KC_L,   KC_SCLN,          KC_QUOT,
             KC_ENT  ,    KC_N,   KC_M,  KC_COMM,KC_DOT, KC_SLSH,          KC_RSFT,
                                  KC_UP, KC_DOWN,KC_LBRC,KC_RBRC,          KC_FN1,
             KC_LALT,        CTL_T(KC_ESC),
             KC_PGUP,
             KC_RCTL, KC_RSFT, KC_SPC
    ),

// linearised
	LAYOUT_ergodox(
			// left hand
			KC_EQL,         
			KC_1,         
			KC_2,   
			KC_3,   
			KC_4,   
			KC_5,   
			KC_LGUI,
			KC_DELT,        
			KC_Q,         
			KC_W,   
			KC_E,   
			KC_R,   
			KC_T,   
			KC_ESC,
			KC_SLSH,        
			KC_A,         
			KC_S,   
			KC_D,   
			KC_F,   
			KC_G,
			KC_LALT,        
			KC_Z,         
			KC_X,   
			KC_C,   
			KC_V,   
			KC_B,   
			KC_TAB,
			LT(SYMB,KC_GRV),
			KC_QUOT,      
			LALT(KC_LSFT),  
			KC_LEFT,
			KC_RGHT,
			KC_TILD,  
			KC_SLSH,
			KC_INS,
			KC_SPC,
			KC_LSFT,
			KC_LCTL,

			// right hand
			KC_RGUI  ,    
			KC_6,   
			KC_7,  
			KC_8,   
			KC_9,   
			KC_0,             
			KC_EQL,
			KC_BSPC ,    
			KC_Y,   
			KC_U,  
			KC_I,   
			KC_O,   
			KC_P,             
			KC_BSLS,
			KC_H,   
			KC_J,  
			KC_K,   
			KC_L,   
			KC_SCLN,          
			KC_QUOT,
			KC_ENT  ,    
			KC_N,   
			KC_M,  
			KC_COMM,
			KC_DOT, 
			KC_SLSH,          
			KC_RSFT,
			KC_UP, 
			KC_DOWN,
			KC_LBRC,
			KC_RBRC,          
			KC_FN1,
			KC_LALT,        
			CTL_T(KC_ESC),
			KC_PGUP,
			KC_RCTL, 
			KC_RSFT, 
			KC_SPC
			)
